//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KickTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAccount
    {
        public long ID { get; set; }
        public long TaskID { get; set; }
        public long AccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Task Task { get; set; }
    }
}
